### PR TITLE
Let `HttpSignatureAuth` prefer the use of `ssh-agent`, if available

### PR DESCRIPTION
**Pull request by der-gabe**
Let `HttpSignatureAuth` prefer the use of `ssh-agent`, if available

### CODE REVIEW

**Comment by der-gabe** [comment]
I honestly don't understand why those tests are failing for Python versions <3.8.

Is this a known issue in `osc-tiny`, or did my changes break it?

**Review by crazyscientist — CHANGES_REQUESTED** [review]
Thank you for the PR to improve usability of `osc-tiny` in interactive programs.

Unfortunately, I cannot agree with your approach to prefer the use of `ssh-agent`, which without doubt is more convenient in interactive sessions, but will pose a risk to non-interactive applications (e.g. on a server).

If the application provides the wrong or no passphrase to `Osc`, one of the SSH commands will eventually open an interactive prompt and ask for the passphrase. And this will effectively freeze a non-interactive server application.

Maybe it would have been less effort and safer to refactor `is_ssh_key_readable` to attempt signing a dummy string?

The sole purpose of this function is to check, whether the key can be read and unlocked in order to use it for signing. My only error was to assume, that it would get the key from the agent, if available.

**Comment by der-gabe** [comment]
I don't understand why these changes should impact `osc-tiny` usage on servers.

If there's no `ssh-agent` running, or it's not accessible (as should be the case on a server) then we fall back to the same logic as before. So if that was broken before, it still is now, but then the problem is in that broken logic that will ask for passwords and freeze the process.

The only newly problematic case would be when the agent is running and accessible and doesn't have the identity referred to in the key, but the key does exist in that location so ssh will later try to ask for the passphrase.

But the old solution didn't work properly, either, because that `ssh-keygen` command we use to check if the key is readable will _never_ use the agent, so it will always prompt for a passphrase.

**Comment by crazyscientist** [comment]
Well, now our discussion will lead to the root cause, that an authentication method for an API should not depend on tools designed for an interactive shell. But that is sadly we cannot do anything about.

My whole point is, why do we need to worry about the internals of SSH in `osc-tiny`? Is there no simpler solution like trying to sign a dummy text (i.e. fixing the incorrect assumption of the current solution)?

Also, we could add the `timeout=` parameter to the `.communicate()` method to ensure that it does not block :thinking:

**Comment by der-gabe** [comment]
I still don't understand how this will "break `osc-tiny` on servers" in any generality. If there's an agent running and it _does_ have the identity, it would even work without a hitch (a case I failed to mention above). AFAICS we're worried about a very unlikely case...

> […] an authentication method for an API should not depend on tools designed for an interactive shell.

That's a fair assessment, but that's what they chose. :shrug: 

> But that is sadly something we cannot do anything about.

Yeah, unfortunately :disappointed: 

> My whole point is, why do we need to worry about the internals of SSH in osc-tiny?

I see what you mean, but OTOH I just built on what was already there... that `ssh-keygen` call to decrypt the private key seems pretty obscure to me. If you regret going down this road now, I get it, but why punish _me_ for it?

> Is there no simpler solution like trying to sign a dummy text (i.e. fixing the incorrect assumption of the current solution)?

I don't understand that, can you elaborate a bit further? What's the incorrect assumption?

And also, is it worth me redoing everything now, or can we leave a more elegant rewrite as a task for the future?

My solution _does_ work (I think).

> Also, we could add the timeout= parameter to the .communicate() method to ensure that it does not block :thinking: 

Absolutely! Good idea! How about 10 seconds?

**Comment by crazyscientist** [comment]
> What's the incorrect assumption?

As our colleague informed us in the GitLab issue, only `ssh-keygen -Y` will contact the agent, but not `ssh-keygen -y`.

As I wrote in my first comment, the function `is_ssh_key_readable` is built on the wrong assumption, that `ssh-keygen -y` would also talk to the agent.

> but why punish me for it?

Please, don't think of this as punishment. The symptom you try to fix are the password prompts, which are caused by an incorrect assumption. But instead of addressing this directly, you created some elaborate code to interact with SSH tools.

So, I'm merely trying to suggest a simpler solution.

**Comment by der-gabe** [comment]
> As our colleague informed us in the GitLab issue […]

(I had figured that out myself, 2 days before him, _and_ posted a comment about it. Just saying...)

> […] only `ssh-keygen -Y` will contact the agent, but not `ssh-keygen -y`.
> 
> As I wrote in my first comment, the function `is_ssh_key_readable` is built on the wrong assumption, that `ssh-keygen -y` would also talk to the agent.

Ah, that's what you meant. OK, but I understood that: That's why _now_ the method will only get called when the agent isn't available anyway, so now it makes sense to use this command. We now fall back to an interactive prompt when the non-interactive option (the agent) has been ruled out.

And if that code were broken on servers, it would have been broken before my changes.

> Please, don't think of this as punishment. The symptom you try to fix are the password prompts, which are caused by an incorrect assumption. But instead of addressing this directly, you created some elaborate code to interact with SSH tools.

Call it elaborate, if you will, but it's very much in line with what was already there before. I don't see how it makes things worse.

> So, I'm merely trying to suggest a simpler solution.

Do you mean this:

> Maybe it would have been less effort and safer to refactor `is_ssh_key_readable` to attempt signing a dummy string?

I mean, sure: Could be that it _would have been_ less effort (not sure what you mean by "safer") to do it that way, but *at this point* it's __more__ effort to throw away a working solution in favour of a rewrite.

If that's what you want then fine, but I would suggest closing this PR then.

**Comment by crazyscientist** [comment]
> And if that code were broken on servers, it would have been broken before my changes.

Yes, that is what I have been writing about in my previous comments: The code was based on a wrong assumption and that code should be fixed, instead of being worked around.

> but at this point it's more effort to throw away a working solution in favour of a rewrite.

TBH, this discussion already took way longer than writing what I had in mind. See #135 :wink:

**Comment by crazyscientist** [comment]
Superseded by #135

**Pull request closed without merging**
